development:
  breeze:
    api: https://breeze-development-api.dashkite.com/
    authority: breeze-development-api.dashkite.com
  oauth:
    redirectURL: http://localhost:3000/oauth
production:
  breeze:
    api: https://breeze-api.dashkite.com/
    authority: breeze-api.dashkite.com
  oauth:
    redirectURL: https://hype.dashkite.com/oauth
