development:
  breeze:
    api: https://breeze-development-api.dashkite.com/
    authority: breeze-development-api.dashkite.com
  # TODO this means you can't login on a deployed dev env
  oauth: http://localhost:3000/oauth

production:
  breeze:
    api: https://breeze-api.dashkite.com/
    authority: breeze-api.dashkite.com
  oauth: https://hype.dashkite.com/oauth
